// Provider utilities for contract deployment and interaction

import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import {
  ZKConfigProvider,
  type ZKIR,
  type ProverKey,
  type VerifierKey,
} from "@midnight-ntwrk/midnight-js-types";
import * as Rx from "rxjs";
import * as fs from "fs";
import * as path from "path";

/**
 * LocalZkConfigProvider - Replaces removed NodeZkConfigProvider from v4 SDK
 * Reads ZK artifacts from disk that are generated by: compact compile <contract> <output_dir>
 */
export class LocalZkConfigProvider<K extends string> extends ZKConfigProvider<K> {
  constructor(private readonly zkArtifactsDir: string) {
    super();
  }

  async getZKIR(circuitId: K): Promise<ZKIR> {
    const irPath = path.join(this.zkArtifactsDir, String(circuitId), "ir");
    const content = fs.readFileSync(irPath, "utf-8");
    return JSON.parse(content) as ZKIR;
  }

  async getProverKey(circuitId: K): Promise<ProverKey> {
    const keyPath = path.join(
      this.zkArtifactsDir,
      String(circuitId),
      "proving_key"
    );
    return fs.readFileSync(keyPath) as unknown as ProverKey;
  }

  async getVerifierKey(circuitId: K): Promise<VerifierKey> {
    const keyPath = path.join(
      this.zkArtifactsDir,
      String(circuitId),
      "verifying_key"
    );
    return fs.readFileSync(keyPath) as unknown as VerifierKey;
  }
}

export async function createWalletProvider(wallet: any) {
  // Get wallet state once to cache keys
  const state = await Rx.firstValueFrom(wallet.state());

  // v5 API: state properties are direct values
  const coinPublicKey = state.coinPublicKey;
  const encryptionPublicKey = state.encryptionPublicKey;

  return {
    coinPublicKey,
    encryptionPublicKey,
    async balanceTx(tx: any, newCoins: any) {
      // v5: wallet methods return promises directly
      const balancedTx = await wallet.balanceTransaction(tx, newCoins);
      return balancedTx;
    },
    async submitTx(tx: any) {
      return wallet.submitTransaction(tx);
    },
  };
}

export async function createContractProviders(
  wallet: any,
  zkConfigPath: string,
  privateStateStoreName: string,
  accountId: string,
  indexerUrl: string,
  indexerWsUrl: string,
  proofServerUrl: string
) {
  const walletProvider = await createWalletProvider(wallet);

  return {
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName,
      accountId,
      privateStoragePasswordProvider: async () => "default-password",
    }),
    publicDataProvider: indexerPublicDataProvider(
      indexerUrl,
      indexerWsUrl
    ),
    zkConfigProvider: new LocalZkConfigProvider(zkConfigPath),
    proofProvider: httpClientProofProvider(proofServerUrl, new LocalZkConfigProvider(zkConfigPath)),
    walletProvider,
    midnightProvider: walletProvider,
  };
}

export async function loadContractModule(contractPath: string) {
  const contractModulePath = path.join(
    process.cwd(),
    contractPath,
    "contract",
    "index.cjs"
  );

  const module = await import(contractModulePath);
  return module;
}
